# Generated by Django 5.2.8 on 2025-12-02 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ath_mobile_handle', models.CharField(help_text='Nombre/comercio en ATH Móvil', max_length=100)),
                ('ath_qr_image', models.ImageField(blank=True, help_text='Imagen del QR de ATH Móvil que verá el cliente para pagar.', null=True, upload_to='ath_qr/')),
                ('session_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('max_clients_per_slot', models.PositiveIntegerField(default=5)),
                ('booking_window_days', models.PositiveIntegerField(default=7, help_text='Cuántos días hacia adelante se puede reservar.')),
                ('cancellation_hours_before', models.PositiveIntegerField(default=12, help_text='Horas mínimas antes para poder cancelar/modificar.')),
                ('custom_instructions', models.TextField(blank=True, help_text='Texto que se mostrará al cliente al finalizar la reserva.')),
                ('show_qr_on_checkout', models.BooleanField(default=True)),
                ('max_slots_per_week_per_client', models.PositiveIntegerField(default=7, help_text='Máx de sesiones por semana por cliente.')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='booking.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.client')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.timeslot')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='booking.trainer'),
        ),
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('slot_capacity', models.PositiveIntegerField(default=5, help_text='Máx clientes por slot en este bloque.')),
                ('active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
