# Generated by Django 5.2.8 on 2026-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_trainer_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('timeslot', 'client'), name='unique_reservation_per_client_timeslot'),
        ),
    ]
