# Generated by Django 5.2.8 on 2026-02-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation_unique_reservation_per_client_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe (Tarjeta)'), ('ATH', 'ATH Móvil')], default='STRIPE', max_length=10),
        ),
    ]
