# Generated by Django 5.2.8 on 2026-02-09 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservation_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe (Card)'), ('ATH', 'ATH Móvil')], default='STRIPE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='booking.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='booking.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout',
            field=models.ForeignKey(blank=True, help_text='Group of reservations for a single payment/checkout', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.checkout'),
        ),
    ]
