# Generated by Django 5.2.8 on 2026-02-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_checkout_reservation_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve the trainer before enabling Stripe onboarding.'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account id (acct_...).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='stripe_onboarded',
            field=models.BooleanField(default=False, help_text='True when Stripe onboarding is completed.'),
        ),
    ]
