# Generated by Django 5.2.8 on 2026-02-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_trainer_is_approved_trainer_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
