# Generated by Django 5.2.8 on 2026-02-10 02:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_trainer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='capacity_per_slot',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8),
        ),
    ]
