# Generated by Django 5.2.8 on 2026-02-14 01:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_trainer_capacity_per_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='max_clients_per_slot',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='capacity_per_slot',
            field=models.PositiveIntegerField(default=5, help_text='Capacidad por slot (por defecto).'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Precio por sesión (por defecto).', max_digits=8),
        ),
    ]
