# Generated by Django 5.2.8 on 2026-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_trainer_max_clients_per_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Override duration for this slot (minutes). If empty, uses trainer.slot_duration_minutes.', null=True),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('trainer', 'date', 'time'), name='unique_timeslot_per_trainer_datetime'),
        ),
    ]
