# Generated by Django 5.2.8 on 2026-02-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_timeslot_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineravailability',
            name='slot_duration_minutes',
        ),
        migrations.AddField(
            model_name='trainer',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutos de descanso/buffer entre sesiones (opcional).'),
        ),
    ]
