# Generated by Django 5.2.8 on 2026-02-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_traineravailability_slot_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad del slot. Si es 0, usa trainer.capacity_per_slot.'),
        ),
    ]
