# Generated by Django 5.2.8 on 2026-02-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_timeslot_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
