# Generated by Django 5.2.8 on 2026-02-23 05:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_stripewebhookevent_trainer_allow_stripe_refunds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeRefundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(blank=True, max_length=255)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('source', models.CharField(choices=[('trainer_portal', 'Trainer portal'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_refund_events', to='booking.checkout')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_refund_events', to='booking.reservation')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_refund_events', to='booking.trainer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
