# Generated by Django 5.2.8 on 2026-02-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_client_user_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='striperefundevent',
            name='source',
            field=models.CharField(choices=[('trainer_portal', 'Trainer portal'), ('client_portal', 'Client portal'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
