# Generated by Django 5.2.8 on 2026-02-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_checkout_confirmation_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='applied_discount_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='applied_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='trainer',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Código de descuento opcional para clientes (ej: VERANO10).', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='discount_percent_off',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de descuento del código (0-100).'),
        ),
    ]
