# Generated by Django 5.2.8 on 2026-02-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_checkout_applied_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='discount_expires_on',
            field=models.DateField(blank=True, help_text='Fecha de expiración del cupón (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='discount_max_uses',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de usos del cupón (0 = sin límite).'),
        ),
    ]
