# Generated by Django 5.2.8 on 2026-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_trainer_discount_expires_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='checkout',
            name='platform_fee_percent_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='checkout',
            name='trainer_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='trainer',
            name='platform_fee_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override de fee de plataforma para este trainer (ej: 10.00). Si está vacío, usa el global.', max_digits=5, null=True),
        ),
    ]
