# Generated by Django 5.2.8 on 2026-02-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_checkout_platform_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation_per_client_timeslot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendee_key',
            field=models.CharField(default='self', max_length=64),
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendee_type',
            field=models.CharField(choices=[('SELF', 'Titular'), ('DEPENDENT', 'Dependiente')], default='SELF', max_length=12),
        ),
        migrations.AddField(
            model_name='clientdependent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='booking.clientprofile'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='booking.clientdependent'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('timeslot', 'client', 'attendee_key'), name='unique_reservation_per_client_timeslot_attendee'),
        ),
        migrations.AddConstraint(
            model_name='clientdependent',
            constraint=models.UniqueConstraint(fields=('profile', 'full_name'), name='unique_dependent_name_per_profile'),
        ),
    ]
