# Generated by Django 5.2.8 on 2026-02-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_usertwofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trainer_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
